"""Console-port reachability check run at agent start (firewall.console_insert_pos + applier glue)."""
import os
import shutil
import tempfile
import unittest
from unittest import mock

from noobrouter_agent import applier, config, firewall

CFG = dict(config.DEFAULTS, lan_if="lan0", wan_if="ppp0", lan_cidr="192.168.50.0/24",
           listen="192.168.50.1", port=8090)
RULE = "-A INPUT -i lan0 -p tcp -m tcp --dport 8090 -j ACCEPT"


def save(policy="ACCEPT", *rules, extra=""):
    body = "\n".join(rules)
    return (f"# Generated by iptables-save\n*filter\n:INPUT {policy} [0:0]\n:FORWARD ACCEPT [0:0]\n"
            f":OUTPUT ACCEPT [0:0]\n{extra}{body}\nCOMMIT\n")


class InsertPosTest(unittest.TestCase):
    def pos(self, text, **kw):
        return firewall.console_insert_pos(text, dict(CFG, **kw))

    def test_open_machine(self):
        self.assertIsNone(self.pos(""))
        self.assertIsNone(self.pos(save()))
        self.assertIsNone(self.pos(save("ACCEPT", "-A INPUT -i ppp0 -j DROP")))

    def test_policy_drop_appends(self):
        self.assertEqual(self.pos(save("DROP", "-A INPUT -i lo -j ACCEPT")), 2)

    def test_trailing_drop_inserts_before_it(self):
        t = save("ACCEPT", "-A INPUT -i lo -j ACCEPT", "-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT",
                 "-A INPUT -j DROP")
        self.assertEqual(self.pos(t), 3)
        self.assertEqual(self.pos(t.replace("-j DROP", "-j REJECT --reject-with icmp-port-unreachable")), 3)

    def test_old_port_rule_does_not_count(self):
        t = save("DROP", "-A INPUT -i lan0 -p tcp -m tcp --dport 8080 -j ACCEPT")
        self.assertEqual(self.pos(t), 2)
        self.assertIsNone(self.pos(t, port=8080))

    def test_existing_accepts(self):
        for r in (RULE, "-A INPUT -i lan0 -j ACCEPT", "-A INPUT -s 192.168.50.0/24 -i lan0 -j ACCEPT",
                  "-A INPUT -s 192.168.50.0/24 -i lan0 -p tcp -m tcp --dport 8090 -j ACCEPT",
                  "-A INPUT -p tcp -m multiport --dports 22,8000:9000 -j ACCEPT",
                  '-A INPUT -i lan+ -p tcp -m tcp --dport 8090 -m comment --comment "web ui -x" -j ACCEPT'):
            self.assertIsNone(self.pos(save("DROP", r)), r)

    def test_unprovable_accepts_do_not_count(self):
        for r in ("-A INPUT -s 192.168.50.10/32 -i lan0 -j ACCEPT",          # one host only
                  "-A INPUT -i lan0 -p tcp -m tcp --sport 1024:65535 -j ACCEPT",
                  "-A INPUT -i lan0 -m limit --limit 5/sec -j ACCEPT",
                  "-A INPUT -i eth9 -j ACCEPT", "-A INPUT -i lan0 -p udp -j ACCEPT"):
            self.assertEqual(self.pos(save("DROP", r)), 2, r)

    def test_drops_that_never_hit_a_new_syn(self):
        t = save("DROP", "-A INPUT -m conntrack --ctstate INVALID -j DROP",
                 "-A INPUT -p tcp -m tcp ! --tcp-flags FIN,SYN,RST,ACK SYN -m conntrack --ctstate NEW -j DROP",
                 "-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,PSH,ACK,URG NONE -j DROP",
                 "-A INPUT -i ppp0 -j DROP", RULE)
        self.assertIsNone(self.pos(t))

    def test_user_chains(self):
        t = save("DROP", "-A INPUT -i lan0 -j lan_in", "-A lan_in -p tcp -m tcp --dport 8090 -j ACCEPT",
                 extra=":lan_in - [0:0]\n")
        self.assertIsNone(self.pos(t))
        t = save("ACCEPT", "-A INPUT -j guard", "-A guard -p tcp -m tcp --dport 22 -j ACCEPT",
                 "-A guard -j DROP", extra=":guard - [0:0]\n")
        self.assertEqual(self.pos(t), 1)  # drop lives in the sub-chain: insert before the jump
        t = save("DROP", "-A INPUT -j noop", "-A noop -i ppp0 -j RETURN", extra=":noop - [0:0]\n")
        self.assertEqual(self.pos(t), 2)

    def test_listen_any(self):
        self.assertEqual(self.pos(save("DROP"), listen="0.0.0.0"), 1)
        self.assertIsNone(self.pos(save("DROP", "-A INPUT -d 192.168.50.1/32 -j ACCEPT")))
        self.assertEqual(self.pos(save("DROP", "-A INPUT -d 192.168.50.1/32 -j ACCEPT"), listen="0.0.0.0"), 2)

    def test_rendered_firewall_already_admits_console(self):
        for lan_all in (True, False):
            m = firewall.normalize(dict(firewall.EMPTY_MODEL, lan_accept_all=lan_all), CFG)
            self.assertIsNone(self.pos(firewall.render_v4(m, CFG)), lan_all)

    def test_fixture_router(self):
        p = os.path.join(os.path.dirname(__file__), "fixtures", "router_iptables_save.txt")
        with open(p, encoding="utf-8") as f:
            text = f.read()
        # legacy router dump: 18 port accepts + ESTABLISHED, then "-A INPUT -j DROP" as rule 19
        self.assertEqual(self.pos(text), 19)
        self.assertIsNone(self.pos(text, port=18080))

    def test_inserted_rule_is_imported_as_own_guard(self):
        live = save("DROP", "-A INPUT -i lo -j ACCEPT", RULE, "-A INPUT -j DROP")
        model, skipped = firewall.import_iptables_save(live, CFG)
        self.assertEqual(model["wan_open"], [])
        self.assertEqual(skipped, [])
        self.assertEqual(firewall.console_rule(CFG), RULE)

    def test_lan_facing(self):
        self.assertTrue(firewall.console_lan_facing(CFG))
        self.assertTrue(firewall.console_lan_facing(dict(CFG, listen="0.0.0.0")))
        for addr in ("127.0.0.1", "10.0.0.1", "::", "bogus"):
            self.assertFalse(firewall.console_lan_facing(dict(CFG, listen=addr)), addr)


class EnsureTest(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.cfg = dict(CFG, data_dir=self.dir, dry_run=False)

    def tearDown(self):
        shutil.rmtree(self.dir)

    def ensure(self, live, **kw):
        calls = []

        def fake_run(argv, **_):
            calls.append(argv)
            return live if "iptables-save" in argv else ""
        with mock.patch.object(applier, "run", side_effect=fake_run):
            return applier.ensure_console_access(dict(self.cfg, **kw)), calls

    def test_inserts_at_position(self):
        res, calls = self.ensure(save("ACCEPT", "-A INPUT -i lo -j ACCEPT", "-A INPUT -j DROP"))
        self.assertEqual(res, "added")
        self.assertEqual(calls[-1], ["iptables", "-I", "INPUT", "2", "-i", "lan0", "-p", "tcp", "-m", "tcp",
                                     "--dport", "8090", "-j", "ACCEPT"])

    def test_netns_prefix(self):
        _, calls = self.ensure(save("DROP"), netns="t1")
        self.assertEqual(calls[-1][:4], ["ip", "netns", "exec", "t1"])

    def test_dry_run_and_noop(self):
        res, calls = self.ensure(save("DROP"), dry_run=True)
        self.assertEqual((res, len(calls)), ("dry_run", 1))
        self.assertEqual(self.ensure(save("DROP", RULE))[0], "ok")
        res, calls = self.ensure(save("DROP"), listen="127.0.0.1")
        self.assertEqual((res, calls), ("loopback", []))

    def test_errors_never_raise(self):
        with mock.patch.object(applier, "run", side_effect=applier.CmdError("command not found: iptables-save")):
            self.assertTrue(applier.ensure_console_access(self.cfg).startswith("error:"))


if __name__ == "__main__":
    unittest.main()
