import unittest

from noobrouter_agent.applier import complete_tables


class CompleteTablesTest(unittest.TestCase):
    def test_empty_input_yields_all_tables(self):
        out = complete_tables("", ("filter", "nat", "mangle"))
        for t in ("*filter", "*nat", "*mangle"):
            self.assertIn(t, out)
        self.assertEqual(out.count("COMMIT"), 3)
        self.assertIn(":PREROUTING ACCEPT [0:0]", out)

    def test_keeps_existing_and_fills_missing(self):
        saved = ("# Generated by iptables-save\n*filter\n:INPUT DROP [0:0]\n:FORWARD ACCEPT [0:0]\n"
                 ":OUTPUT ACCEPT [0:0]\n-A INPUT -i lo -j ACCEPT\nCOMMIT\n# Completed\n"
                 "*raw\n:PREROUTING ACCEPT [0:0]\nCOMMIT\n")
        out = complete_tables(saved, ("filter", "nat"))
        self.assertIn(":INPUT DROP [0:0]", out)
        self.assertIn("-A INPUT -i lo -j ACCEPT", out)
        self.assertIn("*nat", out)
        self.assertNotIn("*raw", out)      # unmanaged tables are never touched
        self.assertNotIn("#", out)


if __name__ == "__main__":
    unittest.main()
